yesdoc/api

- requirements.txt
Se creó el listado con todos los paquetes de Python instalados y requeridos por la aplicación.
Además del paquete **Flask**, son de destacar los paquetes **Flask-RESTful**, **Flask-SQLAlchemy** y **psycopg2**.
> Creación de archivos de requerimientos de pip

- Procfile
- requirements.txt
Se instaló **Gunicorn** para ser usado como servidor HTTP. La creación del **Procfile** permite que *Heroku* haga uso de *Gunicorn* para iniciar la aplicación.
> Instalación de Gunicorn y creación de Procfile

- shippable.yml
Se creó una versión inicial del archivo *shippable.yml*, que permite que el repositorio haga uso de **Shippable** como servidor de integración continua.
> Creación inicial de shippable.yml

- README.md
Se agregó al *README* el badge de **requires.io**, que muestra el estado de los requerimientos de la aplicación y si se encuentran actualizados.
> Incorporación de badge de requires.io al README

- app/config.py
Se hace uso de la variable de entorno **DATABASE_URL** para permitir la configuración de la base de datos desde Heroku, o personalizarla por parte del desarrollador.
En caso de no estar seteada en el equipo, se hace uso del valor por defecto, que es el segundo parámetro de ```os.environ.get```.
> Utilización de variable de entorno DATABASE_URL

- run.py
Se modificaron los parámetros de la aplicación Flask (en particular, el parámetro *host*), para permitir que sea accedida desde equipos de la red, y no sólo desde el servidor.
La documentación pertinente se encuentra en [Externally Visible Server - Flask Documentation](http://flask.pocoo.org/docs/0.10/quickstart/#public-server).
> Configuración de servidor externamente visible

- requirements.txt
Se actualizó **Flask-RESTful** a la versión *0.3.3*. Según el [changelog](https://github.com/flask-restful/flask-restful/blob/master/CHANGES.md#version-033), no se modifica el comportamiento de las funciones utilizadas hasta el momento en el proyecto.
> Actualización de Flask-RESTful a v0.3.3

- run.py
Si bien la ejecución del archivo que inicia la aplicación funcionaba correctamente al hacerlo desde el intérprete de Python, **fallaba desde Gunicorn**, especificando un error ```Connection in use```. Además, debido a que Heroku hace uso de Gunicorn para desplegar la aplicación, era imposible acceder al mismo.
Se implementó un bloque ```__main__```, desde el que se ejecuta la aplicación. Esto corrige el funcionamiento de Gunicorn y, teóricamente, el despliegue en Heroku.
La fuente de la solución encontrada es: [Deploying Flask app to Heroku - “Connection in Use” - Stack Overflow](https://stackoverflow.com/questions/20609570/deploying-flask-app-to-heroku-connection-in-use)
> Creación de bloque '__main__' en archivo de ejecución

- app/__init__.py
Se permite la selección del modo de configuración en base a la variable de entorno ```FLASK_CONFIG_MODE```, pudiendo cambiar de un modo a otro sin hacer modificaciones al código.
Esto también permitirá configurar el servidor de Heroku como **servidor de producción**, mientras los desarrolladores usan la configuración de **development**.
> Selección de modo de configuración a partir de variable de entorno

- app/mod_profiles/resources/measurementList.py
- app/mod_profiles/resources/measurementSourceList.py
- app/mod_profiles/resources/measurementTypeList.py
- app/mod_profiles/resources/measurementUnitList.py
Hasta el momento, se repetía la definición de los campos de cada clase a ser devueltos en las respuestas de la API, tanto en el recurso **View** como **List** de la clase.
Estos cambios eliminan la redundancia, concentrando la definición de los **resource fields** en el recurso *View* de cada clase, y siendo reutilizado por el recurso *List* de la misma.
> Reutilización de 'resource fields' en recursos de listado

- app/mod_profiles/resources/measurementList.py
- app/mod_profiles/resources/measurementSourceList.py
- app/mod_profiles/resources/measurementTypeList.py
- app/mod_profiles/resources/measurementUnitList.py
- app/mod_profiles/resources/profileList.py
Hasta el momento, las solicitudes POST **no retornaban ningún dato**, sólo un estado *HTTP 200* en caso de haberse ejecutado correctamente la solicitud.
Estos cambios proveen a las solicitudes POST la **devolución de la entidad creada**, junto con un estado *HTTP 201* (**Creado**).
> Devolución de entidad creada en solicitud POST

- app/mod_profiles/resources/measurementList.py
- app/mod_profiles/resources/measurementSourceList.py
- app/mod_profiles/resources/measurementSourceView.py
- app/mod_profiles/resources/measurementTypeList.py
- app/mod_profiles/resources/measurementTypeView.py
- app/mod_profiles/resources/measurementUnitList.py
- app/mod_profiles/resources/measurementUnitView.py
- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileList.py
- app/mod_profiles/resources/profileView.py
Se explicitan los argumentos que son **obligatorios** para las solicitudes POST y PUT. Es importante aclarar que no todos los argumentos se han hecho obligatorios, sino sólo aquellos necesarios para el correcto funcionamiento de la aplicación.
> Especificación de argumentos obligatorios para solicitudes de API

- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileView.py
Por defecto, **Flask-RESTful** hace uso del formato **RFC 822** al recuperar los campos de fecha y hora y armar la respuesta JSON. Sin embargo, esto generaba un error *HTTP 500* (Internal Server Error) al querer recuperar cualquier objeto con un campo  de fecha y hora cargado.
En base a la [documentación del campo DateTime](https://flask-restful.readthedocs.org/en/latest/api.html#fields.DateTime), se resolvió al hacer uso del formato **ISO 8601** para los campos de fecha y hora.
Ejemplos de formatos:
* RFC 822
```Fri, 09 Nov 2001 01:08:47 -0000```
* ISO 8601
```2002-12-25 00:00:00-06:39```
> Conversión de campos de fecha y hora a formato 'iso8601'

- app/mod_profiles/resources/measurementView.py
Estos cambios permiten que las solicitudes a recursos de la clase **Measurement** retornen un archivo JSON con la **información completa de sus relaciones**, y no sólo sus IDs.
> Implementación de respuesta JSON de clase Measurement con relaciones

- app/mod_profiles/resources/measurementSourceView.py
- app/mod_profiles/resources/measurementTypeView.py
- app/mod_profiles/resources/measurementUnitView.py
- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileView.py
Estos cambios añaden el campo ```ID``` en toda respuesta JSON de la API. Esto permitirá que, al crear o modificar un objeto, el *frontend* reciba el ID del mismo para mostrar su página asociada.
> Inclusión de campo ID en respuestas de la API

- app/mod_profiles/resources/measurementSourceView.py
- app/mod_profiles/resources/measurementTypeView.py
- app/mod_profiles/resources/measurementUnitView.py
- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileView.py
Estos cambios proveen una **validación** sencilla de los argumentos recibidos en una solicitud **PUT**. También considera que, en caso de no recibirse un argumento relacionado a un campo, éste no debe ser modificado. Así, la forma de vaciar un campo es mediante el **envío explícito del argumento con contenido vacío**.
Además, se corrigió la sintaxis de la actualización de campos, que no permitía el correcto funcionamiento de las solicitudes **PUT**.
> Comprobación de argumentos para actualizaciones PUT

- app/__init__.py
- app/mod_profiles/resources/__init__.py
- app/mod_profiles/resources/profileMeasurementList.py
Se implementó un recurso, accesible desde ```/profiles/<profile_id>/measurements``` mediante **GET**, que retorna todas las mediciones asociadas al perfil especificado.
> Implementación de recurso API de las mediciones de un perfil

- app/__init__.py
- app/mod_profiles/resources/__init__.py
- app/mod_profiles/resources/profileLatestMeasurementList.py
Se implementó un recurso, accesible desde ```/profiles/<profile_id>/measurements/latest``` mediante **GET**, que retorna las **últimas** mediciones asociadas al perfil especificado.
La respuesta incluye la **última medición de cada tipo de medición**, asociada al perfil.
> Implementación de recurso API de las últimas mediciones de un perfil

- requirements.txt
**Flask-RESTful-Swagger** [1] habilita el soporte para **Swagger** [2], que automatiza la creación y la representación de la documentación de la API.
[1] https://github.com/rantav/flask-restful-swagger
[2] http://swagger.io/
> Instalación de Flask-RESTful-Swagger

- app/mod_profiles/resources/genderList.py
- app/mod_profiles/resources/genderView.py
- app/mod_profiles/resources/measurementList.py
- app/mod_profiles/resources/measurementSourceList.py
- app/mod_profiles/resources/measurementSourceView.py
- app/mod_profiles/resources/measurementTypeList.py
- app/mod_profiles/resources/measurementTypeView.py
- app/mod_profiles/resources/measurementUnitList.py
- app/mod_profiles/resources/measurementUnitView.py
- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileLatestMeasurementList.py
- app/mod_profiles/resources/profileList.py
- app/mod_profiles/resources/profileMeasurementList.py
- app/mod_profiles/resources/profileView.py
Se incorporaron los atributos ```resource_fields``` dentro de las clases relacionadas a recursos **View** de la API, para facilitar la asociación de modelos con **Swagger**. [1]
[1] https://github.com/rantav/flask-restful-swagger#using-marshal_with
> Incorporación de atributo 'resource_field' dentro de clases

- app/mod_profiles/resources/genderFields.py
- app/mod_profiles/resources/genderList.py
- app/mod_profiles/resources/genderView.py
- app/mod_profiles/resources/measurementFields.py
- app/mod_profiles/resources/measurementList.py
- app/mod_profiles/resources/measurementSourceFields.py
- app/mod_profiles/resources/measurementSourceList.py
- app/mod_profiles/resources/measurementSourceView.py
- app/mod_profiles/resources/measurementTypeFields.py
- app/mod_profiles/resources/measurementTypeList.py
- app/mod_profiles/resources/measurementTypeView.py
- app/mod_profiles/resources/measurementUnitFields.py
- app/mod_profiles/resources/measurementUnitList.py
- app/mod_profiles/resources/measurementUnitView.py
- app/mod_profiles/resources/measurementView.py
- app/mod_profiles/resources/profileFields.py
- app/mod_profiles/resources/profileLatestMeasurementList.py
- app/mod_profiles/resources/profileList.py
- app/mod_profiles/resources/profileMeasurementList.py
- app/mod_profiles/resources/profileView.py
Se crearon operaciones **Swagger** para todos los recursos existentes hasta el momento. Debido al uso de campos ```fields.Nested```, los atributos ```resource_files``` se trasladaron a nuevas clases **Field** y se actualizaron las referencias a los mismos.
> Creación de versión inicial de documentación Swagger

- README.md
Se actualizó la información básica del ```README``` y se incluyó el nuevo **badge de ```requires.io```**, que hace referencia al nuevo nombre de repositorio.
> Actualización de README y de badge de 'requires.io'

- app/mod_profiles/resources/lists/profileMeasurementList.py
Se añade el filtrado de mediciones obtenidas por el recurso ```/profiles/<id>/measurements```, en base al **tipo, fuente y unidad de medición**. Esto se realiza a través de *parámetros de consulta GET* adicionales a la ruta del recurso.
> Filtrado de mediciones del perfil mediante parámetros de consulta

- app/__init__.py
- app/mod_profiles/models/Gender.py
- app/mod_profiles/models/Measurement.py
- app/mod_profiles/models/MeasurementSource.py
- app/mod_profiles/models/MeasurementType.py
- app/mod_profiles/models/MeasurementUnit.py
- app/mod_profiles/models/Profile.py
- app/mod_profiles/models/User.py
- app/mod_profiles/resources/lists/genderList.py
- app/mod_profiles/resources/lists/measurementList.py
- app/mod_profiles/resources/lists/measurementSourceList.py
- app/mod_profiles/resources/lists/measurementTypeList.py
- app/mod_profiles/resources/lists/measurementTypeUnitsList.py
- app/mod_profiles/resources/lists/measurementUnitList.py
- app/mod_profiles/resources/lists/profileLatestMeasurementList.py
- app/mod_profiles/resources/lists/profileList.py
- app/mod_profiles/resources/lists/profileMeasurementList.py
- app/mod_profiles/resources/lists/userList.py
- app/mod_profiles/resources/views/genderView.py
- app/mod_profiles/resources/views/measurementSourceView.py
- app/mod_profiles/resources/views/measurementTypeView.py
- app/mod_profiles/resources/views/measurementUnitView.py
- app/mod_profiles/resources/views/measurementView.py
- app/mod_profiles/resources/views/profileView.py
- app/mod_profiles/resources/views/userView.py
- app/mod_shared/models/__init__.py
- app/mod_shared/models/db.py
Se creó un nuevo archivo en el módulo ```mod_shared```, que contiene el **objeto de base de datos** a utilizar en forma global.
Además, se especificaron los ```import *``` de modelos existentes, indicando sólo los modelos necesarios.
> Creación de archivo específico para la configuración compartida de base de datos

- app/mod_profiles/models/Profile.py
Se removió de la clase **Profile** el atributo ```gender``` de tipo ```Integer```, que fue reemplazado por una relación con la clase **Gender**.
> Eliminación de atributo 'gender' obsoleto en clase 'Profile'

- app/config.py
Por defecto, el *parser* de **Flask-Restful** sólo devuelve el **primer error** que encuentra en los argumentos de una petición **[1]**. Este cambio configura, **en forma global**, que se especifiquen los errores encontrados en **todos** los argumentos de cada petición.
**[1]** https://flask-restful.readthedocs.org/en/latest/reqparse.html#error-handling
> Especificación del detalle de todos los errores del parser en cada petición

- app/mod_profiles/validators/globalValidator.py
- requirements.txt
Se simplificó el parseo de argumentos *date* y *datetime*, haciendo uso del paquete ```python-dateutil```. Específicamente, de su función de parseo ```parser.parse()``` **[1]**.
Además, se solucionaron los errores de validación relacionados a argumentos *datetime* que contenían un valor de zona horaria, o que no presentaban información acerca de microsegundos.
**[1]** https://labix.org/python-dateutil#head-c0e81a473b647dfa787dc11e8c69557ec2c3ecd2
> Corrección en el parseo de argumentos 'date' y 'datetime'

- app/mod_profiles/resources/views/measurementView.py
- app/mod_profiles/validators/globalValidator.py
Se soluciona el error existente al tratar de **comparar fechas con información de zona horaria y fechas sin esa información**. Además, se convierten todas las zonas horarias a **UTC**, y se almacenan de esa manera en la base de datos.
> Corrección en la comparación de fechas con y sin zona horaria

- app/mod_profiles/common/parsers/measurement.py
- app/mod_profiles/validators/globalValidator.py
Se implementó el validador ```is_previous_datetime()```, que añade la **comprobación de que la fecha y hora recibida no sea posterior a la actual**.
Además, se hace uso del nuevo validador en el *parser* de **Measurement**.
Closes #49
> Implementación del validador de fecha y hora previa

- app/__init__.py
- app/mod_profiles/common/persistence/profile.py
- app/mod_profiles/resources/views/__init__.py
- app/mod_profiles/resources/views/myProfileView.py
Se creó el recurso ```/my/profile```, que hace uso de la **autenticación para obtener la información del perfil** asociado al usuario. Permite los métodos **GET** y **PUT**.
Además, se implementa la lógica de **actualización de un perfil** en el paquete ```common/persistence```, para ser utilizado por los recursos con y sin autenticación.
> Creación de recurso '/my/profile' con autenticación

- app/__init__.py
- app/mod_profiles/common/persistence/user.py
- app/mod_profiles/resources/views/__init__.py
- app/mod_profiles/resources/views/myUserView.py
Se creó el recurso ```/my/user```, que hace uso de la **autenticación para obtener la información del usuario**. Permite los métodos **GET** y **PUT**.
Además, se implementa la lógica de **actualización de un usuario** en el paquete ```common/persistence```, para ser utilizado por los recursos con y sin autenticación.
> Creación de recurso '/my/user' con autenticación

- app/mod_profiles/resources/lists/measurementUnitList.py
Se **elimina el parámetro ```id```** de la lista de parámetros Swagger del recurso ```MeasurementUnitList```, debido a que se mantuvo incorrectamente al copiarlo desde el recurso ```MeasurementUnitView```.
> Corrección de parámetros Swagger en recurso 'MeasurementUnitList'

- app/mod_profiles/resources/views/measurementView.py
Se creó el recurso **DELETE** para una instancia específica de ```Measurement```. Esto permite la eliminación de una medición en particular, lo que retorna un código HTTP **204** en caso de ser exitosa la petición.
> Implementación de recurso DELETE de Measurement

- app/mod_profiles/resources/lists/measurementList.py
- app/mod_profiles/resources/lists/profileList.py
Se eliminan los parámetros de tipo ```path``` existentes en los métodos POST de ```MeasurementList``` y ```ProfileList```, ya que no corresponden. Estos recursos no presentan parámetros de tipo ```path```.
> Eliminación de parámetros Swagger incorrectos en recursos POST

- app/mod_profiles/common/parsers/measurement.py
Se incluye en el *parser* de **Measurement** el argumento ```analysis_id```, para poder atender correctamente las peticiones POST y PUT a los recursos de Measurement.
> Inclusión de parámetro 'analysis_id' en parser de Measurement

- app/mod_profiles/resources/lists/myAnalysisList.py
- app/mod_profiles/resources/lists/myLatestMeasurementList.py
- app/mod_profiles/resources/lists/myMeasurementList.py
- app/mod_profiles/resources/views/myProfileView.py
- app/mod_profiles/resources/views/myUserView.py
Se incluye la respuesta de **código 401** en la documentación Swagger de los recursos que requieren autenticación.
> Inclusión de respuesta Swagger 401 en recursos con autenticación

- app/mod_profiles/common/parsers/measurement.py
- app/mod_profiles/resources/lists/myMeasurementList.py
Se añade el recurso **POST** a ```/my/measurements```, para poder crear una medición asociada al usuario autenticado. No requiere especificar el ```profile_id```, sino que hace uso del perfil del usuario que realiza la petición.
> Implementación de recurso POST para creación de medición con usuario autenticado

- app/mod_profiles/common/parsers/analysis.py
- app/mod_profiles/common/parsers/analysisFile.py
- app/mod_profiles/common/parsers/analysisFileUpload.py
- app/mod_profiles/common/parsers/gender.py
- app/mod_profiles/common/parsers/measurement.py
- app/mod_profiles/common/parsers/measurementSource.py
- app/mod_profiles/common/parsers/measurementType.py
- app/mod_profiles/common/parsers/measurementTypeUnitsList.py
- app/mod_profiles/common/parsers/measurementUnit.py
- app/mod_profiles/common/parsers/profile.py
- app/mod_profiles/common/parsers/profileMeasurementList.py
- app/mod_profiles/common/parsers/storageCredential.py
- app/mod_profiles/common/parsers/storageLocation.py
- app/mod_profiles/common/parsers/user.py
- app/mod_profiles/resources/lists/__init__.py
- app/mod_profiles/validators/generic_validators.py
Se renombra el archivo de validadores a ```generic_validators.py```, y se corrigen algunos detalles en la documentación de sus métodos. Especialmente, se reemplaza el prompt (```>>>```) en los docstrings, que generaba errores en la inspección de código de **PyCharm**.
> Renombrado y corrección a archivo de validadores

- app/config.py
- app/mod_profiles/adapters/dropboxAdapter.py
- app/mod_profiles/adapters/fileManagerFactory.py
- app/mod_profiles/resources/views/analysisFileDownload.py
Se corrige la **gestión de las claves de la aplicación en Dropbox**, incluyendo la clave pública e importando la *clave privada** desde la variable de entorno ```DROPBOX_APP_SECRET```.
Además, se corrige la **devolución de archivos cargados en Dropbox**, y se deja este **servicio de almacenamiento como predeterminado**, en caso de que el usuario no cuente con un servicio asociado.
> Corrección en el manejo de archivos de Dropbox

- app/mod_profiles/adapters/dropboxAdapter.py
- app/mod_profiles/common/persistence/analysisFile.py
- app/mod_profiles/common/swagger/responses/generic_responses.py
- app/mod_profiles/resources/views/analysisFileView.py
Se crea el recurso **DELETE** para eliminar un AnalysisFile específico. El recurso requiere que **el usuario autenticado sea el dueño de la instancia de AnalysisFile**.
Además, se implementa el método propio del **adaptador de Dropbox**, para eliminar un archivo.
> Creación de recurso DELETE en AnalysisFileView

- app/mod_profiles/resources/lists/myAnalysisList.py
Se corrige el funcionamiento del recurso **GET** en ```/my/analyses```, que no retornaba todos los análisis propios, ya que no se obtenían explícitamente los resultados del *query* producto del *backref*.
> Corrección en recurso de obtención de análisis propios

- app/__init__.py
- app/mod_profiles/common/parsers/permission.py
- app/mod_profiles/resources/lists/__init__.py
- app/mod_profiles/resources/lists/analysisAnalysisFileList.py
- app/mod_profiles/resources/lists/analysisMeasurementList.py
- app/mod_profiles/resources/lists/analysisPermissionList.py
- app/mod_profiles/resources/views/analysisFileView.py
- app/mod_profiles/resources/views/permissionView.py
Se crean los recursos **GET** necesarios para obtener las asociaciones de un análisis dado:
* ```/analysis/<analysis_id>/files```: Retorna todas las instancias de ```AnalysisFile``` asociadas al análisis especificado.
* ```/analysis/<analysis_id>/measurements```: Retorna todas las instancias de ```Measurement``` asociadas al análisis especificado.
Además, se corrige el uso de *backref* entre las clases ```Profile``` y ```User```.
> Creación de recursos para obtención de asociaciones del análisis

- app/mod_profiles/resources/lists/myAnalysisList.py
Se ordenan los análisis devueltos por el recurso **GET** en ```/my/analysis```, por fecha y hora, en forma ascendente (de más antiguo a más nuevo).
> Ordenación de análisis propios por fecha y hora

- app/__init__.py
- app/mod_profiles/resources/views/analysisFileView.py
- app/mod_profiles/resources/views/analysisView.py
Se crea el recurso **DELETE** en ```/analysis/<analysis_id>```. Requiere autenticación por parte del dueño del análisis, y **elimina todas las mediciones y archivos asociados al análisis**, junto con el análisis.
> Creación de recurso DELETE para Analysis

- app/__init__.py
- app/mod_profiles/adapters/dropboxAdapter.py
- app/mod_profiles/resources/views/__init__.py
- app/mod_profiles/resources/views/analysisFileThumbnail.py
Se crea el recurso ```/analysis_files/<analysis_file_id>/thumbnail```, para la obtención del *thumbnail* del archivo, mediante **GET**. Actualmente, sólo funciona con archivos alojados en Dropbox.
> Obtención de thumbnails desde Dropbox

- app/mod_profiles/adapters/dropboxAdapter.py
- requirements.txt
En la versión actual de [dropbox/dropbox-sdk-python](https://github.com/dropbox/dropbox-sdk-python) (**3.37**), el método para obtener el **thumbnail** de una imagen no funciona, debido a problemas con *ThumbnailSize*.
Por esto, se implementa el *request* **sin hacer uso del SDK**. El thumbnail se solicita con un tamaño de **640x480**.
> Creación de solicitud para obtener thumbnail de Dropbox, sin usar el SDK

- app/mod_profiles/common/persistence/permission.py
- app/mod_profiles/resources/lists/analysisAnalysisFileList.py
- app/mod_profiles/resources/lists/analysisFileList.py
- app/mod_profiles/resources/lists/analysisMeasurementList.py
- app/mod_profiles/resources/lists/measurementList.py
- app/mod_profiles/resources/lists/myMeasurementList.py
- app/mod_profiles/resources/views/analysisFileDownload.py
- app/mod_profiles/resources/views/analysisFileView.py
- app/mod_profiles/resources/views/analysisView.py
- app/mod_profiles/resources/views/measurementView.py
- app/mod_profiles/resources/views/permissionTypeView.py
- app/mod_profiles/resources/views/permissionView.py
Se implementa el **funcionamiento de los permisos** en los siguientes recursos. En todo caso, se considera al dueño del análisis con permisos totales para ver, editar y eliminar su propia información.
Recurso | Método | Usuario permitido
-------------------------------|--------------------------------------|----------------------------------
```/analysis/<analysis_id>``` | PUT, DELETE | Dueño del análisis.
```/analysis/<analysis_id>/files``` | GET | Dueño del análisis, o con permiso para **ver** los archivos de análisis.
```/analysis_files``` | POST | Dueño del análisis asociado, o con permiso para **editar** los archivos de análisis.
```/analysis_files/<analysis_file_id>``` | GET | Dueño del análisis, o con permiso para **ver** los archivos de análisis. …
> Implementación de lógica para permisos

- app/mod_profiles/resources/views/analysisFileThumbnail.py
Se añade la verificación de permisos en el recurso ```/analysis_files/<analysis_file_id>/thumbnail```
> Verificación de permisos en recurso de obtención de thumbnail

- requirements.txt
- shippable.yml
Se instala ```nose```, y se configura **Shippable** para que ejecute los tests mediante ```nosetests```.
> Configuración de nosetests para Shippable

- app/mod_profiles/resources/lists/analysisPermissionList.py
Se corrige la obtención de los **permisos de un análisis**, al manejar correctamente el *backref* entre ```Permission``` y ```Analysis```.
> Corrección en obtención de permisos de un análisis

- app/mod_profiles/common/parsers/user.py
- app/mod_profiles/common/persistence/user.py
Se deja el argumento ```password``` como opcional para los recursos ```/users/<id>``` y ```/my/user```, en su método **PUT**.
> Eliminación del requerimiento de campo 'password' en recursos PUT para edición de usuarios

- app/mod_profiles/common/parsers/measurementUnit.py
- app/mod_profiles/common/parsers/permissionType.py
- app/mod_profiles/validators/generic_validators.py
Se crea un **validador de variables booleanas** para los recursos de la API. Los valores aceptados son:
* Cadenas: ```"True"``` y ```"False"``` (sin distinguir mayúsculas y minúsculas).
* Enteros: ```1``` y ```0```.
Además, se hace uso de este validador en los parsers de  ```PermissionType``` y de ```MeasurementUnit```.
> Creación de validador para variables booleanas

- app/mod_profiles/common/parsers/measurement.py
- app/mod_profiles/resources/lists/measurementList.py
- app/mod_profiles/resources/lists/myMeasurementList.py
- app/mod_profiles/resources/views/measurementView.py
Se establece como **opcional** el parámetro ```analysis_id``` para los recursos ```/measurements``` y ```/my/measurements``` mediante método **POST**, y el recurso ```/measurements/<id>``` mediante método **PUT**.
> Especificación de análisis opcional para la medición

- app/mod_profiles/resources/views/token.py
Se amplía la **duración del token** de autenticación, a una hora.
> Ampliación de duración token a una hora

- migrations/versions/4312431622eb_creacion_de_permisos_para_comentarios_.py
Se corrige el orden de las migraciones de la base de datos, al modificar la revisión anterior de la migración *"Creación de permisos para comentarios de análisis"*.
> Corrección de orden en migraciones

- app/mod_profiles/resources/lists/groupList.py
Se corrigió el **```import``` del parser** utilizado por el método POST del recurso ```/groups```.
> Corrección de importación de parser en 'groupList'

- app/mod_profiles/resources/lists/analysisPermissionList.py
- app/mod_profiles/resources/lists/groupGroupMembershipList.py
- app/mod_profiles/resources/lists/groupList.py
Para poder utilizar el atributo ```id``` del **recurso recién creado**, antes de realizar ```commit```, se debe efectuar un ```flush``` de la sesión de la base de datos.
> Especificación de 'flush' en sesión de base de datos

- app/mod_profiles/common/persistence/permission.py
Hasta el momento, si el permiso asociado a una acción tenía un valor nulo (```None```), se devolvía este mismo valor al consultar por el permiso, en vez de devolver ```False```.
> Corrección en obtención de permiso con valor 'None'

- app/mod_profiles/resources/lists/groupGroupMembershipList.py
Se corrige la creación de nuevas membresías a un grupo, que **generaba la membresía asociada al usuario autenticado**, y no al perfil del usuario especificado mediante **POST** en ```/groups/<group_id>/members```.
> Corrección en asociación de nueva membresía a perfil especificado

- app/mod_profiles/models/AnalysisComment.py
- app/mod_profiles/models/AnalysisFile.py
- app/mod_profiles/models/GroupMembership.py
- app/mod_profiles/models/Measurement.py
- app/mod_profiles/models/NotificationNewAnalysisFromGroup.py
- app/mod_profiles/models/NotificationNewGroupMembership.py
- app/mod_profiles/models/NotificationNewSharedAnalysis.py
- app/mod_profiles/models/Permission.py
- app/mod_profiles/resources/views/analysisView.py
- app/mod_profiles/resources/views/groupView.py
Se especifican en las relaciones *backref* existentes que corresponde, el **comportamiento en cascada** **[1]**, especialmente para las operaciones de eliminación (*delete*). Además, se elimina la lógica existente en los recursos de la API, que se resuelven automáticamente con el comportamiento en cascada.
**[1]** http://docs.sqlalchemy.org/en/rel_1_0/orm/cascades.html
> Especificación de relaciones backref con comportamiento en cascada

- app/mod_profiles/common/persistence/permission.py
La comprobación de permisos se estaba efectuando incorrectamente, ya que **se hacía uso del permiso y no de su tipo asociado** para realizar la comprobación.
> Corrección en comprobación de permisos de análisis

- app/mod_profiles/common/persistence/analysisFile.py
Se corrige la navegación mediante *backref* entre **Profile** y **User**, en el método para eliminar un archivo de análisis en su ubicación de almacenamiento.
> Corrección en navegación de Profile a User

- app/mod_profiles/models/NotificationNewAnalysisFromGroup.py
- app/mod_profiles/models/NotificationNewGroupMembership.py
- app/mod_profiles/models/NotificationNewSharedAnalysis.py
Se corrigió el formato de las descripciones de notificación, para **escapar correctamente las comillas**.
> Formato correcto de comillas en descripciones de notificaciones

- app/mod_profiles/resources/views/analysisFileThumbnail.py
- app/mod_profiles/resources/views/analysisFileThumbnailByQuery.py
Se añade **soporte para archivos de análisis encriptados**, al solicitar su *thumbnail*. Debido a que el archivo se encuentra encriptado en su ubicación de almacenamiento, **el mismo se desencripta y se retorna en su forma original**, no mediante un thumbnail del mismo.
Los recursos de la API afectados son:
* ```/analysis_files/<analysis_file_id>/thumbnail``` (*GET*)
* ```/analysis_files/<analysis_file_id>/thumbnail_by_query``` (*GET*)
> Obtención de thumbnail para archivos de análisis encriptados

- app/mod_profiles/resources/views/analysisFileThumbnailByQuery.py
Se añade el parámetro booleano opcional ```download``` (por defecto, ```False```), que indica si el *thumbnail* debe visualizarse o **enviarse como adjunto para ser descargado** (```True```).
> Descarga opcional de thumbnail mediante query

- app/mod_profiles/common/parsers/profileGroupMembership.py
- app/mod_profiles/resources/lists/myGroupMembershipList.py
Se añade al recurso ```/my/group_memberships``` (método **GET**) un parámetro *query* opcional de tipo entero: ```group```. El mismo permite filtrar las membresías a partir del identificador único de un grupo.
> Filtrado de membresías de grupo propias, por grupo

- app/mod_profiles/resources/views/permissionView.py
Se añade la especificación de que el recurso para eliminar un permiso (**DELETE** en ```/permissions/<permission_id>```) requiere autenticación.
> Solicitud de autenticación en recurso para eliminar permiso

- app/mod_profiles/resources/lists/analysisFileList.py
- app/mod_profiles/resources/views/analysisFileDownload.py
- app/mod_profiles/resources/views/analysisFileThumbnail.py
- app/mod_profiles/resources/views/analysisFileThumbnailByQuery.py
La obtención de las imágenes de archivos de análisis, y sus respectivos *thumbnails*, fallaba debido a que **se hacía uso de las credenciales de almacenamiento del usuario autenticado**. Por lo tanto, al querer acceder a las mismas mediante un usuario a quien se le ha compartido el análisis, no se encontraban las credenciales correctas, y la imagen no podía ser recuperada.
La solución fue **hacer uso de las credenciales del usuario dueño del análisis**.
> Obtención de imagen y thumbnail en análisis compartidos

- app/mod_profiles/common/fields/notificationFields.py
- app/mod_profiles/common/parsers/notification.py
- app/mod_profiles/models/Notification.py
- app/mod_profiles/models/NotificationNewAnalysisComment.py
- app/mod_profiles/models/NotificationNewAnalysisFromGroup.py
- app/mod_profiles/models/NotificationNewGroupMembership.py
- app/mod_profiles/models/NotificationNewSharedAnalysis.py
- app/mod_profiles/resources/lists/myNotificationList.py
Se añade la especificación del **tipo de notificación**, dividiéndolas en notificaciones de tipo ```message``` (actualmente, sólo los comentarios hechos a un análisis) y tipo ```event```. Además, se añade al recurso de la API ```/my/notifications``` (método **GET**), la posibilidad de especificar el siguiente **parámetro *query* opcional**:
* ```type```: Tipo de notificaciones a retornar. Los tipos posibles son **event** y **message**. Por defecto, se retornan todas las notificaciones. No distingue mayúsculas de minúsculas. **Aclaración**: un valor incorrecto producirá que no se retornen notificaciones.
> Especificación de tipos de notificación

- app/mod_profiles/common/persistence/group.py
- app/mod_profiles/common/persistence/permission.py
Se implementa la **lógica para gestionar el acceso mediante permisos**, cuando la compartición es **por grupos**.
De esta manera, **se valida correctamente la posibilidad de ejecutar una acción por parte de un usuario**, al verificar si se le ha compartido el análisis pertinente a él mismo, o a alguno de sus grupos. En este último caso, se valida que los permisos brindados en su membresía de grupo concuerden con la acción a efectuar.
> Implementación de lógica de permisos por grupo

- app/mod_profiles/common/persistence/permission.py
Se corrige la obtención de **membresías de grupo de un usuario**, al navegar correctamente la relación hacia **Profile** y luego hacia **GroupMembership**.
> Corrección en la obtención de membresías del perfil

- app/mod_profiles/common/parsers/measurementUnit.py
Se permite la inclusión de caracteres numéricos en el campo ```symbol``` de **MeasurementUnit**.
> Eliminación de restricción de números en símbolo de unidad de medición

- app/__init__.py
- app/mod_profiles/models/Gender.py
- app/mod_profiles/models/GroupMembershipType.py
- app/mod_profiles/models/MeasurementSource.py
- app/mod_profiles/models/MeasurementType.py
- app/mod_profiles/models/MeasurementUnit.py
- app/mod_profiles/models/PermissionType.py
- app/mod_profiles/models/StorageLocation.py
- app/mod_profiles/models/TypeUnitValidation.py
Se añaden los **valores por defecto** en los parámetros de los constructores, para soportar correctamente la **creación de nuevos objetos** desde *Flask-Admin*. **[1]**
Además, se quita la opción de **creación de usuarios** desde *Flask-Admin*.
**[1]** https://stackoverflow.com/questions/17254840/unable-to-create-models-on-flask-admin
> Especificación de valores por defecto en constructores, para Flask-Admin
